# Generated by Django 4.2.6 on 2023-10-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecosystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_CODE', models.IntegerField(unique=True)),
                ('EcosystemName', models.CharField(max_length=255)),
                ('EcosystemType', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('Salinity', models.CharField(max_length=255)),
                ('NorthernLat', models.FloatField(blank=True, null=True)),
                ('NrangeNS', models.CharField(blank=True, max_length=10, null=True)),
                ('SouthernLat', models.FloatField(blank=True, null=True)),
                ('SrangeNS', models.CharField(blank=True, max_length=10, null=True)),
                ('WesternLat', models.FloatField(blank=True, null=True)),
                ('WrangeEW', models.CharField(blank=True, max_length=10, null=True)),
                ('EasternLat', models.FloatField(blank=True, null=True)),
                ('ErangeEW', models.CharField(blank=True, max_length=10, null=True)),
                ('Climate', models.CharField(blank=True, max_length=255, null=True)),
                ('TotalCount', models.IntegerField(blank=True, null=True)),
                ('TotalFamCount', models.IntegerField(blank=True, null=True)),
                ('TotalComplete', models.IntegerField(blank=True, null=True)),
                ('LatDegFill', models.IntegerField(blank=True, null=True)),
                ('LatMinFill', models.IntegerField(blank=True, null=True)),
                ('NorthSouthFill', models.CharField(blank=True, max_length=1, null=True)),
                ('LongDegFill', models.IntegerField(blank=True, null=True)),
                ('LongMinFill', models.IntegerField(blank=True, null=True)),
                ('EastWestFill', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
